application:
  name: jpapi
  project: jpapi
  cloud_region: aws/us-east-2
  publicly_accessible: true
routers:
- name: main
  custom_domains:
  - branch: master
    domain: jpapi.polv.cc
  routes:
  - application_name: jpapi
    paths:
    - /
